services:
  backend:
    build: ./backend
    container_name: scoreops-backend
    ports:
      - "3001:3001"
    env_file:
      - .env
    restart: unless-stopped


  frontend:
    build: ./frontend
    container_name: scoreops-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
